name: Deploy backend to ECR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - 'backend/**'  
    branches: [ master ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '10'  # Use Node.js version 18

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 3: Set CalVer tag
    - name: Set CalVer tag
      id: set-tag
      run: echo "TAG=$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_ENV

    # Step 4: Optional: Log in to Docker Hub and push Docker image
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2 #give your region

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY : ${{vars.ECR_BACKEND_REPOSITORY}}
      run: |
        cd backend
        echo "Building Docker image with tag: $TAG"
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
        
    # Step 5.1: Download current ECS task definition
    - name: Download current task definition
      run: |
        aws ecs describe-task-definition \
          --task-definition dev-backend \
          --query taskDefinition > task-definition.json

    # Step 5.2: Clean the task definition by removing metadata
    - name: Clean task definition
      run: |
        jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .deregisteredAt, .registeredBy, .enableFaultInjection)' task-definition.json > cleaned-task-definition.json
        mv cleaned-task-definition.json task-definition.json

    - name: Render updated task definition
      id: render-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY : ${{vars.ECR_BACKEND_REPOSITORY}}
        AWS_REGION: ap-southeast-2      
      with:
        task-definition: ./deployments/ecs-dev-backend-task-definition.json
        container-name: dev-backend
        wait-for-service-stability: true
        image: $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
        environment-variables: |
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION=${{ env.AWS_REGION }}    

    # Step 7: Deploy the new task definition to the ECS service
    - name: Deploy to ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.render-task-def.outputs.task-definition }}
        service: dev-backend-service-q1dlri6e
        cluster: dev-backend-cluster
        wait-for-service-stability: true          